[project]
authors = ["Shlok Natarajan <shlok.natarajan@gmail.com>"]
channels = ["conda-forge"]
name = "TxGNN-Burkitts"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
dgl = ">=2.3.0,<3"
pandas = ">=2.2.3,<3"
numpy = ">=1.26.4,<2"
tqdm = ">=4.67.1,<5"
matplotlib = ">=3.10.1,<4"
ipykernel = ">=6.29.5,<7"
scikit-learn = ">=1.6.1,<2"
goatools = ">=1.4.12,<2"
pytorch = ">=2.3.1,<3"
wandb = ">=0.19.10,<0.20"

