[project]
authors = ["Shlok Natarajan <shlok.natarajan@gmail.com>"]
channels = ["conda-forge", "pytorch", "pypi"]
name = "TxGNN-Burkitts"
platforms = ["osx-arm64"]
version = "0.1.0"

[dependencies]
python = "3.8.*"

[tasks]

[pypi-dependencies]
dgl = "==0.5.2"

