[project]
authors = ["Shlok Natarajan <shlok.natarajan@gmail.com>"]
channels = ["conda-forge", "pytorch", "pypi"]
name = "TxGNN-Burkitts"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.8.*"
pandas = "<2.0.0"
numpy = ">=1.24.4,<2"
tqdm = ">=4.67.1,<5"
matplotlib = ">=3.7.3,<4"
scikit-learn = ">=1.3.2,<2"
goatools = ">=1.4.12,<2"
pytorch = "1.7.1.*"
cudatoolkit = "11.0.*"
ipykernel = ">=6.29.5,<7"
jupyter = ">=1.1.1,<2"
requests = "2.25.1.*"
urllib3 = "1.26.6.*"
idna = "2.10.*"
certifi = "2020.12.5.*"
charset-normalizer = "2.0.12.*"
loguru = ">=0.7.2,<0.8"

[tasks]

[pypi-dependencies]
dgl = "==0.5.2"

