[project]
authors = ["Shlok Natarajan <shlok.natarajan@gmail.com>"]
channels = ["conda-forge", "pytorch", "pypi"]
name = "TxGNN-Burkitts"
platforms = ["osx-arm64"]
version = "0.1.0"

[dependencies]
python = "3.8.*"
pandas = "<2.0.0"
pytorch = "2.0.*"
torchvision = "0.15.*"
torchaudio = "2.0.*"
torchdata = "0.6.*"
pip = ">=24.3.1,<25"
ipykernel = ">=6.29.5,<7"
tqdm = ">=4.67.1,<5"
scikit-learn = ">=1.3.2,<2"
matplotlib = ">=3.7.3,<4"
goatools = ">=1.4.12,<2"

[tasks]

[pypi-dependencies]
dgl = "==1.1.2"

